import React from 'react'

export { default as Anchor } from './lib/components/Anchor'
export { default as Button } from './lib/components/Button'
export { default as ButtonAnchor } from './lib/components/ButtonAnchor'
export { default as GymPhoto } from './lib/components/GymPhoto'
export { default as H1 } from './lib/components/H1'
export { default as H2 } from './lib/components/H2'
export { default as H3 } from './lib/components/H3'
export { default as Input } from './lib/components/Input'
export { default as Paragraph } from './lib/components/Paragraph'
export { default as Select } from './lib/components/Select'
export { default as TextPlaceholder } from './lib/components/TextPlaceholder'

export { default as theme } from './lib/theme'
export { default as anchorStyle } from './lib/mixins/anchorStyle'
export { default as buttonStyle } from './lib/mixins/buttonStyle'
export { default as coloredStyle } from './lib/mixins/coloredStyle'
export { default as headingStyle } from './lib/mixins/headingStyle'
export { default as inputStyle } from './lib/mixins/inputStyle'
export { default as marginStyle } from './lib/mixins/marginStyle'

export { default as GlobalFonts } from './lib/GlobalFonts'
